### ISSUE TITLE
After delete category I lost my products - change action behavior to none

### ISSUE THREAD

**Issue by Kipoderax** [Kipoderax/IdeaSpend#92]
If I'm an owner of the category name X
   then after delete category also products 
   assigned to category X are deleting

**Comment by Kipoderax** [comment]
New user should have default catalog for no assigned products or products which lost catalog (after deleted)

**Comment by wiotrek** [comment]
I think that it is not a bug, because this is a correct behavior in cascade relation. In my opinion change model relation on restrict is enough to solve issues

**Comment by Kipoderax** [comment]
True, delete cascade is on
